### ISSUE TITLE
Package Error : version error

### ISSUE THREAD

**Issue by mono300genuine** [nurmandev/template-61#2]
-  plz delete `package-lock.json` file.
-  rename `pnpm-lock copy.yaml` into `pnpm-lock.yaml`
- only run `pnpm install` command for installing required module.
- then `pnpm start` command to run remotion studio.

Dont need to run `npm install` command...
this repo only use pnpm command.
plz update above requirements in next commit...

**Comment by nurmandev** [comment]
Done
